### ISSUE TITLE
2.2 之后可以自定义preview-template, 只需要把app里的template复制到工程下就行

### ISSUE THREAD

**Issue by zetaztt** [potato47/ccc-devtools#10]

**Comment by zetaztt** [comment]
将ccc-devtools解压到工程目录后需要将所有路径中的'app/editor/static/preview-templates/'去除直接使用'ccc-devtools/...'即可

**Comment by potato47** [comment]
ok，我也试过了，后面会添加到说明里。

区别是放到工程目录里只能单个项目使用，原来的方式可以所有项目使用。

**Comment by zetaztt** [comment]
这样方便多人协作, 不用所有人都安装一遍了, 只要更新仓库就行
