### ISSUE TITLE
3.0版本，竖屏游戏 顶部区域被 顶部状态栏遮挡

### ISSUE THREAD

**Issue by tjunxin** [potato47/ccc-devtools#16]
![image](https://user-images.githubusercontent.com/4941309/82719985-dd253800-9ce1-11ea-9ecc-caced78955c7.png)

引擎版本：2.2.2

**Comment by potato47** [comment]
右上角设备选择可以不用default，改为高度小一点的设备，另外看一下index.html是否修改正确，看样子你上面的toolbar并没有对齐，是不是没有去掉原来的toolbar代码

**Comment by tjunxin** [comment]
> 右上角设备选择可以不用default，改为高度小一点的设备，另外看一下index.html是否修改正确，看样子你上面的toolbar并没有对齐，是不是没有去掉原来的toolbar代码

找到原因了，旧版本是在jade中添加include ./ccc-devtools/index.html，新版本直接替换了引擎的topbar，更新时没注意。感谢！
