### ISSUE TITLE
mac os 怎么弄成全局的呢

### ISSUE THREAD

**Issue by ckcfcc** [potato47/ccc-devtools#17]
macos 下的 ccc 没有 static 目录 也没有 *.jade文件

**Comment by potato47** [comment]
有的，点击 creator 右上角的编辑器按钮就能进入Resources目录
![image](https://user-images.githubusercontent.com/21299133/84340548-8f5e6a00-abd3-11ea-94cc-de040aad506f.png)

**Comment by nimohe** [comment]
`/Applications/CocosCreator/Creator/2.4.2/CocosCreator.app/Contents/Resources/static/preview-templates`
macOS是有这个路径的，command+shift+g 快捷键直接跳转到目录（跳转之前注意软件版本号）。
