### ISSUE TITLE
CocosCreator 2.4.2 获取纹理缓存时报错

### ISSUE THREAD

**Issue by nimohe** [potato47/ccc-devtools#20]
## 问题描述
点击`查看纹理缓存`按钮之后报错
```
vue.min.js:6 TypeError: Cannot read property 'name' of undefined
at Object.cc.cache (cc-console-utils.js:137)
at wn.openCacheDialog (preview.js:152)
at He (vue.min.js:6)
at HTMLButtonElement.n (vue.min.js:6)
at HTMLButtonElement.Yr.o._wrapper (vue.min.js:6)  
```

## 原因
cocosCreator2.4.2 缓存的数据结构变动导致获取数据报错。

### 举例
比如下面是在版本2.4.2，获取的单个纹理的数据结构：
```
item: cc_EffectAsset
    isValid: true
    loaded: true
    name: "builtin-2d-graphics"
    nativeUrl: ""
    properties: null
    refCount: 2
    shaders: [{…}]
    techniques: [{…}]
    __asyncLoadAssets__: undefined
    __depends__: undefined
    _effect: Effect {_dirty: true, _name: "builtin-2d-graphics", _technique: Technique, _techniques: Array(1), _asset: cc_EffectAsset}
    _name: "builtin-2d-graphics"
    _native: ""
    _nativeAsset: undefined
    _nativeDep: undefined
    _nativeUrl: ""
    _objFlags: 0
    _ref: 2
    url: ""
    _uuid: "30682f87-9f0d-4f17-8a44-72863791461b"
    __proto__: cc_Asset
  
```

https://github.com/potato47/ccc-devtools/blob/6bf387626219f42325015a27abb66b70d993f4ac/libs/js/cc-console-utils.js#L119-L151
`cc-console-utils.js` 中的`cach`方法中获取的item对象：
- content 节点
- type 节点
通通都都不见了 😂

## 测试附件📎 
说明：附件是2.4.2编辑器自带的 helloworld-typescript项目
[test-ccc-devtools.zip](https://github.com/potato47/ccc-devtools/files/5060836/test-ccc-devtools.zip)

## ✅ 解决方法

在这段代码后添加: `if(!item.content) item.content=item; `
https://github.com/potato47/ccc-devtools/blob/6bf387626219f42325015a27abb66b70d993f4ac/libs/js/cc-console-utils.js#L124

[方法来自论坛回复](https://forum.cocos.org/t/ccc-devtools/91496/47)

## API 升级建议
https://github.com/potato47/ccc-devtools/blob/6bf387626219f42325015a27abb66b70d993f4ac/libs/js/cc-console-utils.js#L120

[官方文档 v2.4 资源管理模块升级指南](https://docs.cocos.com/creator/manual/zh/release-notes/asset-manager-upgrade-guide.html)

// 由于v2.4资源管理模块，所以获取缓存的代码，可替换成cc.assetManager来获取。

`let rawCacheData = cc.assetManager.assets._map;`

**Comment by potato47** [comment]
感谢反馈，已修复，2.4版本可以使用2d-v2.4分支
