### ISSUE TITLE
2.4.3 win10 无法查看缓存资源，报错如图

### ISSUE THREAD

**Issue by lizhiyu-me** [potato47/ccc-devtools#23]
![QQ图片20201223123943](https://user-images.githubusercontent.com/24876673/102960087-252c6780-451c-11eb-9d6e-e539107693c0.png)

**Comment by potato47** [comment]
master适用于2.0-2.3版本，2.4要切换到2d-v2.4分支

**Comment by lizhiyu-me** [comment]
太棒了，比插件商店里面的inspector+好用多了。我之前还以为插件商店的inspector是你做的，准备支持一波，结果买了才发现不是
