### ISSUE TITLE
点击label 或者 node 节点时 报错

### ISSUE THREAD

**Issue by 296230428** [potato47/ccc-devtools#5]
![image](https://user-images.githubusercontent.com/19701441/59004843-bca06b80-884d-11e9-9175-6e8653033d67.png)

**Comment by potato47** [comment]
是最新的版本么，上一次merge修复过一次重复点击报错问题

**Comment by 296230428** [comment]
最新版的2.3.0 确实是反复点击报的错

**Comment by 296230428** [comment]
> 是最新的版本么，上一次merge修复过一次重复点击报错问题

最新版 还有就是点击标志位置出现几率大

**Comment by potato47** [comment]
creator是什么版本呢

**Comment by 296230428** [comment]
2.0.10

**Comment by potato47** [comment]
我一直用的2.1.1，没遇到过报错问题，如果有必现的步骤或demo就好了

**Comment by 296230428** [comment]
稍等 我用个新工程 试着重现下

**Comment by 296230428** [comment]
额 2.0.10 新建一个空白工程加了几个精灵 反复点击就出现了 
![image](https://user-images.githubusercontent.com/19701441/59488853-3ae6b880-8eb3-11e9-92ad-23a2fb1519d9.png)
![image](https://user-images.githubusercontent.com/19701441/59488864-44702080-8eb3-11e9-9a80-28776ffcd4e6.png)

**Comment by potato47** [comment]
只有2.1以下版本才会报错，之前改了但是没更新版本号，我刚才又提交了一遍，你pull下来再试一下

**Comment by 296230428** [comment]
好的 我试下

**Comment by 296230428** [comment]
恩 没问题了 就是不显示版号了

**Comment by 296230428** [comment]
有版号了 我重新刷新就好了
