### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by 0x2CA** [potato47/ccc-devtools#8]
![image](https://user-images.githubusercontent.com/19868292/70587769-c85a5980-1c05-11ea-9c66-186cb38759dd.png)
Can't show Tree

**Comment by potato47** [comment]
2.2.1的bug，我找时间修一下

**Comment by wulei** [comment]
@potato47 好像不是2.2.1的问题，我是升级了chrome发现的

**Comment by potato47** [comment]
是新版本chrome问题，与拖拽区域的组件冲突，暂时去掉了这个组件，现在可以用了
