### ISSUE TITLE
在调试信息里的信息怎么不能实时更新？

### ISSUE THREAD

**Issue by wyd124** [potato47/ccc-devtools#9]
cocos creator v2.2.2 版本， chrome 版本 74.0.3729.108（正式版本） （64 位）。
在creator里点击运行按钮在浏览器里运行demo，然后打开插件的调试信息面板，demo里的node 在移动，但是调试信息面板里node的位置信息不变，只有重新鼠标点击相应的node节点，位置信息才会刷新。 调试面板的自动刷新开发打开/关闭都试了，也不行。

请问这个问题怎么解决？

**Comment by potato47** [comment]
2.2 以上有问题，我找时间看一下

**Comment by potato47** [comment]
发了新版，修复了2.x版本的问题，欢迎体验
